service: cs-group-${self:custom.stageVars.groupNumber}-${self:custom.stageVars.myFirstname}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'Fn::GetAtt': [Table, Arn]
  environment:
    tableName: ${self:service.name}-dynamodb

functions:
  hello:
    handler: functions/hello.handle
    events:
      - http:
          path: hello
          method: get

  get:
    handler: functions/Palier1/get.handle
    events:
      - http:
          method: post
          path: items/movies/
          cors:
            origin: http://localhost:3000
            allowCredentials: true

  create:
    handler: functions/Palier1/create.handle
    events:
      - http:
          method: post
          path: items
          cors:
            origin: http://localhost:3000
            allowCredentials: true

  list:
    handler: functions/Palier1/list.handle
    events:
      - http:
          method: get
          path: items/{type}
          cors:
            origin: http://localhost:3000
            allowCredentials: true
  rate:
    handler: functions/Palier2/rate_movie.handle
    events:
      - http:
          method: post
          path: items/movies/rate
          cors:
            origin: http://localhost:3000
            allowCredentials: true
  delete:
    handler: functions/Palier2/delete_movie.handle
    events:
      - http:
          method: post
          path: items/movies/delete
                     
custom:
  stageVars: ${file(./stage.${self:provider.stage}.yml)}

resources:
  - ${file(resources/dynamodb.yml)}