Resources:
    Table:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:service.name}-dynamodb
            AttributeDefinitions:
                - AttributeName: type
                  AttributeType: S
                - AttributeName: uuid
                  AttributeType: S
                - AttributeName: name
                  AttributeType: S
                - AttributeName: score
                  AttributeType: M
                - AttributeName: participation
                  AttributeType: L
                - AttributeName: category
                  AttributeType: S

                
            KeySchema:
                - AttributeName: type
                  KeyType: HASH
                - AttributeName: uuid
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
